### ISSUE TITLE
Own handling of MANIFEST.SKIP incompatible with ExtUtils::Manifest

### ISSUE THREAD

**Issue by mohawk2** [reneeb/Test-CheckManifest#20]
See https://perldoc.pl/ExtUtils::Manifest :

> The file MANIFEST.SKIP may contain regular expressions of files that should be ignored by mkmanifest() and filecheck(). The regular expressions should appear one on each line. Blank lines and lines which start with `#` are skipped. Use `\#` if you need a regular expression to start with a `#`.

You are treating `MANIFEST.SKIP` as if it is literals. This means that if one has the line:

> `.git\/`

in `MANIFEST.SKIP`, this used to work, but you have now made it not work. That is compatible neither with your 1.31, nor with EUM.

Note to other users: this entire module can be replaced with this code:

```
use strict;
use warnings;
use Test::More tests => 2;
use ExtUtils::Manifest;

is_deeply [ ExtUtils::Manifest::manicheck() ], [], 'missing';
is_deeply [ ExtUtils::Manifest::filecheck() ], [], 'extra';
```

**Comment by reneeb** [comment]
Thanks. Will work on this and add a section in the docs with your replacement code...

**Comment by racke** [comment]
What was the reason for the change ... looks like it is going to break a lot of modules where I'm using this module for testing the manifest.

**Comment by reneeb** [comment]
This should be fixed with 4feb4decc486d .

It was an oversight by me. The bug was introduced to fix a warnings as absolute paths on Windows had something like "...\Test-Check". The regex warned as "\T" is an unknown escape sequence, that's why I used "\Q...\E".

But I was tackling the bug in the wrong place... So I restored old behaviour.

If you still experience any problems, please drop me a line.

**Comment by racke** [comment]
Still fails for me .. 1.38 works fine .. all later versions from 1.39 above cause the manifest to fail. This also happens in the Travis builds.

**Comment by reneeb** [comment]
Ok. Which repository? I'll try to make a test case for that...

**Comment by racke** [comment]
https://github.com/interchange/interchange6-schema

The following entries in the MANIFEST.SKIP file are exposing the problem:

```
^\.git\/
^sql\/
```

Thanks for the quick answers!

**Comment by toddr** [comment]
Test::MockFile is failing over this too on travis: https://travis-ci.org/CpanelInc/Test-MockFile/jobs/515483575

It is supposed to be honoring the items in MANIFEST.SKIP as regexes but this doesn't seem to be working at the moment.  The repo can be found here: https://github.com/cpanelinc/Test-MockFile

**Comment by toddr** [comment]
This issue first shows up in e4efb7a1dac51fcdcd166447d15e482250ced310

**Comment by choroba** [comment]
@mohawk2 : It seems your alternative solution doesn't work with `perl -T`, while the previous solution did.

    Insecure dependency in chdir while running with -T switch

**Comment by mohawk2** [comment]
@choroba Why oh why would you run a manifest-test with `-T`?? ;-)

**Comment by choroba** [comment]
@mohawk2: That's what e.g. Module::Starter does in its boilerplate tests :man_shrugging:
